### PR TITLE
Switch from servlet-api to javax.servlet-api

### PR DESCRIPTION
**Pull request by adriens**
upgrade `artifactId` from `servlet-api` to `javax.servlet-api`

### CODE REVIEW

**Comment by adriens** [comment]
This is related to  #3

**Comment by adriens** [comment]
@noemienicolas : can you try it on your workstation ?

**Comment by adriens** [comment]
if it's ok, merge it please.

**Comment by noemienicolas** [comment]
Ca fonctionne sur ma machine ! youhou

**Pull request merged**
